//Simple example generated by ChatGPT as an addition to memory1.c to demonstrate dynamic data allocation (heap)
#include <stdio.h>
#include <stdlib.h>

// Global variable
// Stored in the program's global/static memory region (.data)
int globalVar = 100;

void demonstrateMemory() {
    // Static local variable
    // Stored in the global/static memory region (.data)
    static int staticVar = 200;

    // Regular local variable
    // Stored on the stack
    int localVar = 300;

    // Dynamic memory allocation #1
    // malloc() allocates memory on the heap
    int *heapInt = malloc(sizeof(int));
    *heapInt = 400;

    // Dynamic memory allocation #2
    // Another allocation on the heap
    int *heapArray = malloc(5 * sizeof(int));
    heapArray[0] = 500;

    printf("=== Variable Values ===\n");
    printf("globalVar : %d\n", globalVar);
    printf("staticVar : %d\n", staticVar);
    printf("localVar  : %d\n", localVar);
    printf("*heapInt  : %d\n", *heapInt);
    printf("heapArray[0] : %d\n\n", heapArray[0]);

    printf("=== Virtual Addresses ===\n");

    // Global/static memory region
    printf("globalVar       : %p\n", (void *)&globalVar);
    printf("staticVar       : %p\n", (void *)&staticVar);

    // Stack memory
    printf("localVar        : %p\n", (void *)&localVar);

    // Stack memory (the pointers themselves)
    printf("&heapInt        : %p\n", (void *)&heapInt);
    printf("&heapArray      : %p\n", (void *)&heapArray);

    // Heap memory (the dynamically allocated blocks)
    printf("heapInt points to   : %p\n", (void *)heapInt);
    printf("heapArray points to : %p\n", (void *)heapArray);

    // Release the heap memory when finished
    free(heapInt);
    free(heapArray);
}

int main() {
    demonstrateMemory();
    return 0;
}