//Simple example generated by ChatGPT to demonstrate static storage and stack storage

#include <stdio.h>

// Global variable -> Stored in static/global memory (.data)
int globalVar = 100;

void demonstrateMemory() {
    // Static local variable -> Stored in static/global memory (.data)
    static int staticVar = 200;

    // Regular local variable -> Stored on the stack
    int localVar = 300;

    void *x = &globalVar; //initialize x

    printf("Address of globalVar: %p\n", x); //using x from line 15
    printf("Address of staticVar: %p\n", (void *)&staticVar);
    printf("Address of localVar : %p\n", (void *)&localVar);
}

int main() {
    demonstrateMemory();
    return 0;
}

