//The following example was generated by ChatGPT

#include <stdio.h>
#include <pthread.h>

void *worker(void *arg) {
    for (int i = 1; i <= 5; i++) {
        printf("Worker thread: %d\n", i);
    }
    return NULL;
}

int main() {
    pthread_t thread_one; //I'm creating a thread struct

    // Create a new thread
    //First parameter:Address of a pthread_t variable
    //Second parameter Thread attributes (stack size, scheduling, etc.) NULL means “use the default settings”
    //Third parameter: The function the new thread should execute
    //Fourth parameter: Data passed to the thread function. NULL means “don’t pass any data”
    //All in all, this means: “Create a new thread, use default settings, run the worker function, and don’t pass it any data.”
    pthread_create(&thread_one, NULL, worker, NULL);

    // Main thread continues running
    for (int i = 1; i <= 5; i++) {
        printf("Main thread: %d\n", i);
    }

    // Wait for the worker thread to finish
    //First parameter: The thread you want to wait for
    //Second parameter:Used to receive the thread’s return value. NULL means the program will ignore whatever the return value is
    pthread_join(thread_one, NULL);

    return 0;
}