// Simple example generated by ChatGPT

#include <stdio.h>
#include <pthread.h>

// Shared variable (still shared between threads)
int counter = 0;

// How many times each thread will increment
const int ITERATIONS = 100000;

// Mutex (lock) used to protect the shared variable
pthread_mutex_t lock;

// Thread function
void* increment(void* arg) {
    for (int i = 0; i < ITERATIONS; i++) {

        // 🔒 LOCK: only ONE thread can enter this critical section at a time
        pthread_mutex_lock(&lock);

        // -------------------------------
        // CRITICAL SECTION START
        // -------------------------------
        // Now this update is SAFE because no other thread can interfere

        counter++;

        // -------------------------------
        // CRITICAL SECTION END
        // -------------------------------

        // 🔓 UNLOCK: allow other threads to enter
        pthread_mutex_unlock(&lock);
    }

    return NULL;
}

int main() {
    pthread_t t1, t2;

    // Initialize the mutex before using it
    pthread_mutex_init(&lock, NULL);

    // Create two threads that run concurrently
    pthread_create(&t1, NULL, increment, NULL);
    pthread_create(&t2, NULL, increment, NULL);

    // Wait for both threads to finish
    pthread_join(t1, NULL);
    pthread_join(t2, NULL);

    // Expected result is ALWAYS correct now
    printf("Final counter value: %d\n", counter);

    // Clean up the mutex after use
    pthread_mutex_destroy(&lock);

    return 0;
}