// Simple example generated by ChatGPT
#include <stdio.h>
#include <pthread.h>

// Shared variable (both threads access this)
int counter = 0;

// Number of increments each thread will do
const int ITERATIONS = 100000;

// Thread function
void *increment(void *arg) {
    for (int i = 0; i < ITERATIONS; i++) {
        // ❗ RACE CONDITION HERE
        // This is NOT atomic. It actually happens in steps:
        // 1. Read counter from memory
        // 2. Add 1
        // 3. Write result back
        counter++;
    }
    return NULL;
}

int main() {
    pthread_t t1, t2;
    // Create two threads running the same function
    
    pthread_create(&t1, NULL, increment, NULL);
    pthread_create(&t2, NULL, increment, NULL);

    // Wait for both threads to finish
    pthread_join(t1, NULL);
    pthread_join(t2, NULL);

    // Expected value: 200000
    // Actual value: usually LESS due to lost updates
    printf("Final counter value: %d\n", counter);

    return 0;

}